name = "testing_pkg"
uuid = "f8e86250-39dd-40bf-9dea-7402c13ae12f"
authors = ["Jakob Hoffmann"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
